INSERT INTO ingredients(name, is_indexable) VALUES
("Flour", true),
("Milk", true),
("Eggs", true),
("Butter", true),
("Vegetable oil", true),
("Olive oil", true),
("Garlic", true),
("Onions", true),
("Chicken", true),
("Rice", true),
("Potatoes", true),
("Cheese", true),
("Cottage cheese", true),
("Beef", true),
("Carrots", true),
("Cream", true),
("Yogurt", true),
("Sugar", false),
("Salt", false),
("Pepper", false),
("Paprika", false),
("Nutmeg", false);
